spring:
  application:
    name: UserCenter
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lordbao
    password: 123456
    url: jdbc:mysql://localhost:3306/code_nav_user_center
server:
  port: 8080
